FROM node:18 AS build

WORKDIR /usr/src/app

RUN apt update && \
   apt install -y wget netcat && \
   wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
   chmod +x /usr/bin/wait-for

COPY package*.json ./

RUN npm install -y

COPY . .

EXPOSE 3000
